name: Master CICD

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

on:
  # Runs on pushes on main
  push:
    branches: [ "main" ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Install mkdocs
        run: pip install mkdocs-material mkdocs-glightbox

      - name: Copy Root Md files to docs
        shell: bash
        run: |
          cp -f CONTRIBUTING.md docs/CONTRIBUTING.md
          cp -f README.md docs/HOME.md

      - name: Build Docs
        run: mkdocs build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: "site/"

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
