name: PR CI

# Allow one concurrent build per head ref
concurrency:
  group: ${{ github.head_ref }}
  cancel-in-progress: true

on:
  # Runs on PR against main
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Install mkdocs
        run: pip install mkdocs-material mkdocs-glightbox

      - name: Copy Root Md files to docs
        shell: bash
        run: |
          cp -f CONTRIBUTING.md docs/CONTRIBUTING.md
          cp -f README.md docs/HOME.md

      - name: Build Docs
        run: mkdocs build
